CREATE TABLE consumers(	
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar
(50),
address	varchar
(30),
zip	varchar
(10),
phone	VARCHAR,
email	varchar

(25),
password	varchar
(25)
);



CREATE TABLE providers	(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
address	varchar
(80),
zip	varchar
(10),
phone	varchar
(30),
name	varchar
(50),
email	varchar
(50),
password	varchar
(25),
type	varchar
(25)

);

CREATE TABLE dishes	(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
provider_id	INTEGER REFERENCES providers
(id) ON
DELETE CASCADE NOT NULL,
name	varchar(50),
description
varchar
(255),
price	NUMERIC
(8,2),
image varchar
(255)
);

CREATE TABLE orders	(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
provider_id	INTEGER REFERENCES providers
(id) ON
DELETE CASCADE NOT NULL,
consumer_id	INTEGER
REFERENCES consumers
(id) ON
DELETE CASCADE NOT NULL,
created	TIMESTAMPTZ
NOT NULL default NOW
(),
status	varchar
(50)
);


CREATE TABLE order_items(	
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
order_id	INTEGER REFERENCES orders
(id) ON
DELETE CASCADE NOT NULL,
dish_id	INTEGER
REFERENCES dishes
(id) ON
DELETE CASCADE NOT NULL,
qty	INTEGER
);

